# Generated by Django 4.1.3 on 2023-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("steps", models.IntegerField()),
                ("minutesWalk", models.IntegerField()),
                ("burnedEnergy", models.IntegerField()),
                ("dateTimeActivity", models.DateField()),
            ],
            options={
                "verbose_name": "UserHealth",
                "verbose_name_plural": "UsersHealth",
            },
        ),
    ]
