# Generated by Django 4.1.3 on 2023-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_userhealth_age_userhealth_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhealth",
            name="age",
        ),
        migrations.RemoveField(
            model_name="userhealth",
            name="gender",
        ),
        migrations.AlterField(
            model_name="userhealth",
            name="dateTimeActivity",
            field=models.DateTimeField(),
        ),
    ]
