# Generated by Django 4.1.3 on 2023-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_remove_userhealth_age_remove_userhealth_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealth",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userhealth",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
